account_id = "{my account ID here}"
name = "worker-template"
compatibility_date = "2022-03-12"
workers_dev = false
main = "./src/index.js"
routes = [
  "my.url.com/*",
  "my.url.com"
]

kv_namespaces = [
  { binding = "{NAME}", id = "{ID here}", preview_id = "{preview/dev ID here}" },
]

# [durable_objects]
# bindings = [
#   { name = "Counter", class_name = "Counter" },
# ]

# [[migrations]]
# tag = "v1"
# new_classes = ["Counter"]
